CREATE TABLE ncei_climate91(
  station varchar(11),
  valid date,
  high real,
  low real,
  precip real,
  snow real,
  max_high real,
  max_low real,
  min_high real,
  min_low real,
  max_precip real,
  years int,
  gdd32 real,
  gdd41 real,
  gdd46 real,
  gdd48 real,
  gdd50 real,
  gdd51 real,
  gdd52 real,
  sdd86 real,
  max_high_yr   int[],
  max_low_yr    int[],
  min_high_yr   int[],
  min_low_yr    int[],
  max_precip_yr int[],
  max_range     smallint,
  min_range smallint,
  hdd65 real,
  cdd65 real,
  srad real
);
ALTER TABLE ncei_climate91 OWNER to mesonet;
CREATE UNIQUE INDEX ncei_climate91_idx on ncei_climate91(station,valid);
GRANT SELECT on ncei_climate91 to nobody;
